name: Sync Forks

on:
  schedule:
    - cron: '0 */2 * * *' # Runs every 2 hours
  workflow_dispatch: # Allows manual trigger

jobs:
  sync-forks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/milk-net/milk-net.github.io.git
          git fetch upstream

      - name: Sync Fork with Upstream
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories -X ours
          git checkout --ours CNAME
          
          git push origin main # or master if that's your default branch

      - name: Clean up
        run: git remote remove upstream
